version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony-network

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - symfony-network
  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /nuxt
    ports:
      - ${FRONTEND_PORT:-3000}:3000
      - ${FRONTEND_PORT2:-24678}:24678
    command: sh init.sh
#    frontend:
#      build: ./frontend
#      volumes:
#        - type: bind
#          source: ./frontend
#          target: /nuxt
#      ports:
#        - ${FRONTEND_PORT:-3000}:3000
#        - ${FRONTEND_PORT2:-24678}:24678
#      command: sh init.sh
#  frontend:
#    build:
#      dockerfile: docker/frontend/Dockerfile
#      context: ./frontend
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    ports:
#      - ${FRONTEND_PORT:-3000}:3000
#      - ${FRONTEND_PORT2:-24678}:24678
#    command: yarn dev
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony_app
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - symfony-network

volumes:
  mysql_data:

networks:
  symfony-network:
    driver: bridge
